#!/bin/bash

# STEP 1: Create a temp dir with all the files.
TEMP_DIR=$(mktemp -d)
cp -r ./cap/* $TEMP_DIR/

# STEP 2: Compile/edit files in temp dir.
sed -i

# STEP 3: Safely apply changes to .cap dir.
rsync --delete -r $TEMP_DIR/ .cap/

# STEP 4: Cleanup the temp dir.
rm -r $TEMP_DIR
