#!/bin/bash -x
# This script installs the systemd files on a server.
# Meant to be run in the repo's base directory.

REPO_DIR=$PWD
REPO_USER=alanxoc3
REPO_GROUP=alanxoc3

echo "This is the repo: '${REPO_DIR}'."
echo "This is the user/group to use: '${REPO_USER}:${REPO_GROUP}'."
echo

pushd /etc/systemd/system/

cat << EOF | sudo tee gemini-server.service > /dev/null
[Unit]
Description=The Gemini Server for my blog.

[Service]
ExecStart=${REPO_DIR}/server/gemini_server ${REPO_DIR}
WorkingDirectory=${REPO_DIR}

[Install]
WantedBy=multi-user.target
EOF

cat << EOF | sudo tee gemini-proxy.service > /dev/null
[Unit]
Description=The Gemini to Http proxy for my blog. Nginx calls this.

[Service]
ExecStart=${REPO_DIR}/server/http_server

[Install]
WantedBy=multi-user.target
EOF

cat << EOF | sudo tee gemini-git-pull.service > /dev/null
[Unit]
Description=Updates the folder for git. Meant to be called by a timer.

[Service]
ExecStartPre=git fetch
ExecStart=git merge
WorkingDirectory=${REPO_DIR}
User=${REPO_USER}
Group=${REPO_GROUP}

[Install]
WantedBy=multi-user.target
EOF

cat << EOF | sudo tee gemini-git-pull.timer > /dev/null
[Unit]
Description=Update git repo 4 times an hour.

[Timer]
OnCalendar=*:0/15
AccuracySec=1m
Persistent=true

[Install]
WantedBy=timers.target
EOF

# Reload all the files we just added.
sudo systemctl daemon-reload

# Enable the services.
sudo systemctl enable gemini-server.service
sudo systemctl enable gemini-proxy.service
sudo systemctl enable gemini-git-pull.timer

# And start them.
sudo systemctl restart gemini-server.service
sudo systemctl restart gemini-proxy.service
sudo systemctl restart gemini-git-pull.timer

# Assumes these commands have already been run as well.
# If I have to set up a new server, I'll actually automate this.
# sudo pacman -S certbot-nginx nginx-mainline
# sudo systemctl enable nginx.service
# sudo systemctl start nginx.service
# sudo certbot --nginx

# For the https proxy, copy over the nginx config file.
sudo cp ${REPO_DIR}/server/nginx.conf /etc/nginx/nginx.conf
sudo nginx -s reload
